sonar.projectKey=pagopa_idpay-portal-merchants-frontend
sonar.organization=pagopa

# Exclude files from coverage analysis (aligns with Jest)
sonar.coverage.exclusions=\
  src/bootstrap.tsx,\
  src/index.js,\
  src/reportWebVitals.ts,\
  src/api/generated/**,\
  src/__mocks__/**

# Optionally also exclude generated sources from all analysis
sonar.exclusions=src/api/generated/**
