const env = import.meta.env;

export const ENV = {
  ENV: env.VITE_ENV,

  PUBLIC_URL: env.BASE_URL || '/portale-esercenti',

  CONFIG: {
    HEADER: {
      OPERATION_MANUAL_LINK: env.VITE_PAGOPA_HEADER_OPERATION_MANUAL_LINK,
    },
    FOOTER: {
      LINK: {
        PRIVACYPOLICY: env.VITE_PAGOPA_FOOTER_PRIVACYPOLICY,
        PROTECTIONOFPERSONALDATA:
          env.VITE_PAGOPA_FOOTER_PROTECTIONOFPERSONALDATA,
        TERMSANDCONDITIONS: env.VITE_PAGOPA_FOOTER_TERMSANDCONDITIONS,
        ACCESSIBILITY: env.VITE_PAGOPA_FOOTER_ACCESSIBILITY,
      },
    },
  },

  ASSISTANCE: {
    EMAIL: env.VITE_PAGOPA_HELP_EMAIL,
    LINK: env.VITE_PAGOPA_HELP_LINK,
  },

  URL_FE: {
    PRE_LOGIN: env.VITE_URL_FE_PRE_LOGIN,
    LOGIN: env.VITE_URL_FE_LOGIN,
    LOGOUT: env.VITE_URL_FE_LOGOUT,
    LANDING: env.VITE_URL_FE_LANDING,
    ASSISTANCE_MERCHANT: env.VITE_URL_FE_ASSISTANCE_MERCHANTS,
  },

  URL_API: {
    MERCHANTS: env.VITE_URL_API_MERCHANTS,
    MERCHANTS_PORTAL: env.VITE_URL_API_MERCHANTS_PORTAL,
    ROLE_PERMISSION: env.VITE_URL_API_ROLE_PERMISSION,
    EMAIL_NOTIFICATION: env.VITE_URL_API_EMAIL_NOTIFICATION,
  },

  API_TIMEOUT_MS: {
    MERCHANTS_PORTAL: Number(env.VITE_API_MERCHANTS_PORTAL_TIMEOUT_MS),
    MERCHANTS: Number(env.VITE_API_MERCHANTS_TIMEOUT_MS),
    ROLE_PERMISSION: Number(env.VITE_API_ROLE_PERMISSION_TIMEOUT_MS),
    EMAIL_NOTIFICATION: Number(env.VITE_API_EMAIL_NOTIFICATION_TIMEOUT_MS),
  },

  URL_INSTITUTION_LOGO: {
    PREFIX: env.VITE_URL_INSTITUTION_LOGO_PREFIX,
    SUFFIX: env.VITE_URL_INSTITUTION_LOGO_SUFFIX,
  },

  ANALYTCS: {
    ENABLE: env.VITE_ANALYTICS_ENABLE === 'true',
    MOCK: env.VITE_ANALYTICS_MOCK === 'true',
    DEBUG: env.VITE_ANALYTICS_DEBUG === 'true',
    TOKEN: env.VITE_MIXPANEL_TOKEN,
    API_HOST:
      env.VITE_MIXPANEL_API_HOST ?? 'https://api-eu.mixpanel.com',
  },

  ONE_TRUST: {
    OT_NOTICE_CDN_URL: env.VITE_ONE_TRUST_OTNOTICE_CDN_URL,
    OT_NOTICE_CDN_SETTINGS:
      env.VITE_ONE_TRUST_OTNOTICE_CDN_SETTINGS,
  },
};
